target_table: playground_max.dune_labels
columns_ddl: "address String, label String, introduced_at DateTime, source LowCardinality(String)"
partition_expr: "toStartOfMonth(introduced_at)"
order_by_expr: "address, label, introduced_at"
target_columns: "address, label, introduced_at, source"

dune_query_id_full: "5718056"
dune_query_id_daily: "5718249"
csv_schema: "address String, label String, introduced_at String, source String"
select_list: "address, label, parseDateTimeBestEffort(introduced_at) AS introduced_at, source"

date_range_predicate: "parseDateTimeBestEffort(introduced_at) BETWEEN toDateTime('{{START_DT}}') AND toDateTime('{{END_DT}}')"
backfill_days: 30
date_backfill_predicate: "parseDateTimeBestEffort(introduced_at) BETWEEN start_dt AND end_dt"