target_table: playground_max.gnosis_daily_bluechip_prices
columns_ddl: "block_date Date, symbol LowCardinality(String), price Float64"
partition_expr: "toStartOfMonth(block_date)"
order_by_expr: "symbol, block_date"
target_columns: "block_date, symbol, price"

dune_query_id_full: "5701957"
dune_query_id_daily: "5701962"
csv_schema: "block_date String, symbol String, price Float64"
select_list: "toDate(parseDateTimeBestEffort(block_date)) AS block_date, symbol, toFloat64(price) AS price"

# skipped dedup for reliability now; can add later
date_range_predicate: "toDate(parseDateTimeBestEffort(block_date)) BETWEEN toDate('{{START_DATE}}') AND toDate('{{END_DATE}}')"
backfill_days: 30
date_backfill_predicate: "toDate(parseDateTimeBestEffort(block_date)) BETWEEN start_dt AND end_dt"